export const searchBarDropdownType = {
  SHOW_DROPDOWN: "SHOW_DROPDOWN",
  HIDE_DROPDOWN: "HIDE_DROPDOWN"
};

export const modalLoginType = {
  SHOW_LOGIN_MODAL: "SHOW_LOGIN_MODAL",
  HIDE_LOGIN_MODAL: "HIDE_LOGIN_MODAL"
};

export const modalRegisterType = {
  SHOW_REGISTER_MODAL: "SHOW_REGISTER_MODAL",
  HIDE_REGISTER_MODAL: "HIDE_REGISTER_MODAL"
};