export const authType = {
  AUTH: "AUTH",
  LOGOUT: "LOGOUT",
  USER_LOADING: "USER_LOADING",
  USER_LOADED: "USER_LOADED",
  AUTH_ERROR: "AUTH_ERROR",
  USER_UPDATE: "USER_UPDATE"
}

export const adsType = {
  FETCH_ADS: "FETCH_ADS",
  POST_AD: "POST_AD",
  FETCH_AD: "FETCH_AD",
  UPDATE_AD: "UPDATE_AD",
  REMOVE_AD: "REMOVE_AD",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  FILTER_BY_SEARCH: "FILTER_BY_SEARCH",
  FILTER_POSTED_BY_USER: "FILTER_POSTED_BY_USER",
  DELETE_AD_POSTED_BY_USER: "DELETE_AD_POSTED_BY_USER",
};

export const errorType = {
  GET_ERRORS: "GET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
};

